language: node_js
node_js:
  - node
sudo: false
install:
- npm install
script: echo "npm test temporarily disabled"
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_f426b365063b_key -iv $encrypted_f426b365063b_iv
  -in deploy_key.enc -out ../../.ssh/deploy_key -d
- eval "$(ssh-agent -s)"
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- ssh -i ./deploy_key $USER@$ADDR_IP pwd